# Copied from VulkanCore.jl
# Based on https://github.com/vsg-dev/VulkanSceneGraph/blob/master/.github/workflows/ci.yml
name: CI

on:
  push:
  pull_request:

env:
  JULIA_GITHUB_ACTIONS_CI: ON

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.7', '1.8', '1.9', '1.10', 'nightly']
        os: [ubuntu-latest, macos-12, macos-13, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
